name: npm run build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build && cat .next/server/app/index.html
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
